# Build settings
markdown: kramdown
highlighter: rouge

# Site settings
title: "Teaching Machines"
description: > # this means to ignore newlines until "email:"
   MIT Press (2021)

email: mail@audreywatters.com
#blog logo
logo: "/assets/images/new_hack_logo.jpg"
logo2: "/assets/images/beless.png"
# blog cover
cover: "/assets/images/susan.jpg"

name: 'Audrey Watters'
author: 'Audrey Watters'
author_image: "/assets/images/author.jpg"

paginate:	10
paginate_path: "/blog/page:num"
permalink: /:categories/:year/:month/:day/:title 

url: "http://teachingmachin.es" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@hackeducation'

# social icons and sharing options
social:
  - icon:   twitter
    url:    https://twitter.com/hackeducation
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&url="

  - icon:   facebook
    url:    https://facebook.com/history.future.education
    desc: Like me on facebook
    share_url: http://www.facebook.com/sharer/sharer.php
    share_title: ?title=
    share_link: "?u="

  - icon:   github
    url:    https://github.com/audreywatters/teachingmachines
    desc:   Fork me on github
    share_url: 
    share_title:
    share_link:

 # - icon:  google-plus
 #   url:   
 #   desc:  
 #   share_url:
 #   share_title:
 #   share_link:

  - icon: rss
    url:  http://teachingmachin.es/feed.xml
    desc: Subscribe
    share_url:
    share_title:
    share_link:

  - icon: envelope
    url:  mailto:mail@audreywatters.com
    desc: Email
    share_url:
    share_title:
    share_link:    
  
